### PR TITLE
Install gnupg as dependency for node

### LINKED ISSUE #157: Project setup fails at node installation step
Running `docker-compose build` fails with the following message.

```
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
(23) Failed writing body
```

I think installing `gnupg` before `nodejs` should fix the issue.

### PR DESCRIPTION
**Pull request by arun1595**
Fixes #157

### CODE REVIEW

**Comment by StareIntoTheBeard** [comment]
Hey there, @arun1595. Thanks so much for your contribution. I made an update to master this morning to try and fix TravisCI -- would you mind pulling it into your branch?

**Comment by arun1595** [comment]
@StareIntoTheBeard Sure, let me pull the changes and try it.

**Comment by arun1595** [comment]
@StareIntoTheBeard I just tried `sudo docker-compose build` after pulling the changes in the latest commit. I am still facing the same issue mentioned in #157

**Comment by StareIntoTheBeard** [comment]
@arun1595, sorry that commit on master was trying to fix the travis build rather than docker. Let me pull your branch and see if i can replicate/help troubleshoot.

**Comment by arun1595** [comment]
@StareIntoTheBeard Yeah, I just had a look at the changes :smile:

**Comment by StareIntoTheBeard** [comment]
Your branch builds successfully for me in Docker, are you still having an issue, @arun1595?

**Comment by arun1595** [comment]
@StareIntoTheBeard I am unable to build from `master` because we're missing the installation of `gnupg` which this PR adds

**Comment by StareIntoTheBeard** [comment]
@arun1595 is it possible for you to just sync master into your branch?

**Comment by arun1595** [comment]
@StareIntoTheBeard It is in sync with `master`

**Pull request merged**
