### PR TITLE
Check user account exist before attempting to create one in seed task

### LINKED ISSUE #185: Running the seed mix task after running once throws constraint error
#### Summary

Running the seed task for the second time throws the constraint error as we don't check if the user account with the email in question already exists.

#### Stacktrace

```
Starting ExqUI on Port 4040
[debug] QUERY OK db=1.3ms
begin []
[debug] QUERY ERROR db=165.8ms
INSERT INTO "users" ("email","failed_attempts","first_name","last_name","password_hash","revenue_rate","roles","sign_in_count","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ["admin@example.com", 0, "Joe", "Admin", "$2b$12$XgUXHTx3ipopQvWHvjkwPu0khqOmZTYWtT5TMv/PIgbiadFtwBdzi", #Decimal<0.600>, ["admin", "sponsor", "developer"], 0, {{2018, 6, 3}, {21, 55, 12, 86094}}, {{2018, 6, 3}, {21, 55, 12, 86107}}, <<68, 65, 123, 123, 255, 188, 73, 1, 164, 226, 31, 28, 156, 78, 56, 245>>]
[debug] QUERY OK db=0.1ms
rollback []
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * unique: users_email_index

If you would like to convert this constraint into an error, please
call unique_constraint/3 in your changeset and define the proper
constraint name. The changeset has not defined any constraint.

    (ecto) lib/ecto/repo/schema.ex:574: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/ecto/repo/schema.ex:559: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto) lib/ecto/repo/schema.ex:222: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:774: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/schema.ex:125: Ecto.Repo.Schema.insert!/4
    (code_fund) lib/code_fund/seed.ex:12: Mix.Tasks.CodeFund.Seed.seed/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```

#### Proposed solution

We should check if user account with a given email already exists using `Repo.get_by` before trying to create one.

### PR DESCRIPTION
**Pull request by arun1595**
Fixes #185

### CODE REVIEW

**Comment by StareIntoTheBeard** [comment]
Hey @arun1595, thanks for your contribution. Can we follow the pattern in the `factory.ex` file to solve this issue? Rather than check the database for presence of a user, let's let it create a new one by appending a UUID to the email address.

https://github.com/gitcoinco/codefund/blob/master/lib/code_fund/factory.ex#L8

**Comment by StareIntoTheBeard** [comment]
@arun1595 Also, be sure to run `mix format` prior to your commits so the build doesn't fail in Travis.

**Comment by arun1595** [comment]
@StareIntoTheBeard Ah, that's a better way to solve this issue.

Let me update my PR.

**Comment by arun1595** [comment]
@StareIntoTheBeard There's an issue with using the sequence defined in the factory. When the seed task is run for the first time, the users get the email addresses `user-0@example.com`, `user-1@example.com` and `user-2@example.com`

When the task is run again, the ids start from 0 again. So, the factory tries to insert a user account with the email address `user-0@example.com` which fails the unique constraint. The factory pattern is suitable for tests but not for seeding :disappointed: 

How should we go about addressing this issue? What do you think?
`

**Comment by arun1595** [comment]
@StareIntoTheBeard Btw, the following test fails in the travis build:

```
1) test GET / it runs the query correctly without excluded countries set (CodeFundWeb.API.AudienceMetricsControllerTest)
     test/code_fund_web/controllers/api/audience_metrics_controller_test.exs:89
     Assertion with == failed
     code:  assert json_response(conn, 200) == %{"property_count" => 1, "impression_count" => 31, "unique_user_count" => 2}
     left:  %{"property_count" => 1, "unique_user_count" => 2, "impression_count" => 21}
     right: %{"property_count" => 1, "unique_user_count" => 2, "impression_count" => 31}
     stacktrace:
       test/code_fund_web/controllers/api/audience_metrics_controller_test.exs:101: (test)
```

I am not sure why this test fails. Can you please take a look?

**Comment by StareIntoTheBeard** [comment]
@arun1595 Couple of things -- I have the test passing in a branch i'm working in, i'm pretty scattered at the moment and there are a lot of things in flux surrounding the feature in question for this test so I'm in the middle of figuring this out now. The other thing is about the seed data, we should make the items use a UUID so there's no collusion.

**Comment by arun1595** [comment]
@StareIntoTheBeard I've updated my PR to make use of UUID when generating unique email addresses. Check it out when you get a chance.

Thanks!

**Pull request closed without merging**
